### ISSUE TITLE
Update dependencies to `polkadot-v0.9.16`

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-pallets#105]
We shall update the pallet dependencies to `polkadot-v0.9.16`, at least for NFT pallet as there're already projects (FairSquare) working based on it.

Some work has already been done here: https://github.com/Fair-Squares/litentry-pallets/pull/1

TODOs:
- update `orml_nft` dep too
- update dep for other pallets, otherwise you'll get compilation errors as they are members in the same workspace and combined dependency can happen.

**Comment by wangminqi** [comment]
The version is far too old and litentry-pallet has mostly been removed and abandoned.
