### ISSUE TITLE
Devise a future plan for NFT pallet

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-pallets#106]
We shall start to think about how the NFT pallet should be developed:

- Do we manage it in `litentry-pallets` or `litentry-parachain` repo?
- Which underlying infrastructure shall we use, `orml_nft` or `pallet_unique`?
- Alignment to the upstream (e.g. #105)
- What kind of use cases are we aiming at? E.g. from NFT workshop, from cooperations with FairSquare
- Do we develop it in a usecase-oriented way, or try to figure out the abstraction of it that **could** be used by other products later? (I prefer the former, as it could be too general to implement given that NFT is merely a bunch of bytes and it's the usecase which interprets the bytes)

I can image we would almost certainly need a rewriting.

Tagging @hanwencheng @geastwood @h4n0 @wangminqi

**Comment by ndkazu** [comment]
Hello Kailai,
I was planning on adding a fractional-nft transaction to the litentry-nft pallet for future use in the FairSquare pallet. 
We definitely would like to use the latest implementation of your pallet, especially if dependencies such as the "orml-nft" one are modified in any way after the re-write.

**Comment by wangminqi** [comment]
Task halted until specific NFT requirement comes.
