### ISSUE TITLE
Distribute Drop3 campaign rewards on Litmus

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-pallets#107]
For @geastwood 

Steps:
1. Execute all 4 calls through Polkadot JS with sudo. Calls can be found: https://github.com/litentry/crowdloan-distributor/blob/litmus-drop3/encoded_call.txt#L2-L9

**Comment by jingleizhang** [comment]
- [ ] Drop3 will provide the reward list in JSON format 
- [ ] Most of these rewards will be vested in 30 days

**Comment by Reminiscense** [comment]
We have announced to the community of the token distribution : https://medium.com/@litentry/drop3-community-testing-reward-distribution-d687d3cdb56f

**Comment by geastwood** [comment]
Done
