### ISSUE TITLE
signature algorithms of Evm and Substrate on TEE

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-pallets#116]

**Comment by Kailai-Wang** [comment]
I think it goes to the wrong repo :(

This pallet is deprecated. It should either go to the parachain repo or tee-worker repo

**Comment by Kailai-Wang** [comment]
I should have archived this repo

**Comment by jingleizhang** [comment]
Issue moved to [litentry/tee-worker #28](https://github.com/litentry/tee-worker/issues/28) via [**ZenHub**](https://www.zenhub.com/)
