### ISSUE TITLE
Use PalletId for NFT pot

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/litentry-pallets#80]
**Description**
Current Treasury Pot in NFT pallet is in Config an AccountID, therefore in runtime/lib.rs, we need to have a hardcoded accountId of treasury Pallet (since dynamic generation there is not possible). For the sake of automation and maintenance, it's better to change it to PalletId and use another function inside NFT to convert from PalletId to AccountId.
Cons: 1. There is one more call in Create Class. 2 Not possible to change the beneficiary address to something other than a pallet.

**Acceptance Criteria**
- [ ] Change pot to PalletId
- [ ] Have a conversion function from PalletId to AccountId
- [ ] have a issue at upstream to modify runtime/lib.rs

**Comment by wangminqi** [comment]
Ancient archived issue. No longer needed.
