### ISSUE TITLE
Have tokenId in related events

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/litentry-pallets#81]
**Description**
Token instances generated by Mint, Claim, Merge does not have TokenId in the accompanying events, need to have it for front end to better track them. NB orml_nft::mint returns the TokenId. For mint, we may chose to use the first/last token id + quantity

**Acceptance Criteria**
- [ ] Add tokenId in events when mint, claim, merge succeed

**Comment by wangminqi** [comment]
Only one problem. 
This is our current mint event:   MintedToken(T::AccountId, T::AccountId, ClassIdOf<T>, u32),
As mint method is allowed for a quantity input, so should we generate multiple mint event for each individual token, or add two extra parameters( start token id, end token id) to replace quantity.

I suggest the latter one. extra parameters( start token id, end token id) to replace quantity.

**Comment by bdmason** [comment]
If token ID is an auto incrementing integer, then the user would need to know the existing token IDs in order to specify the start token ID. E.g. if token IDs 1, 2 & 3 already existed, the user would need to start with token ID 4. That feels very awkward.

**Comment by StamfordDigital** [comment]
Wouldn't it be better to keep the quantity and return an array of token IDs on a single mint event?

**Comment by Satoshi-Kusumoto** [comment]
> If token ID is an auto incrementing integer, then the user would need to know the existing token IDs in order to specify the start token ID. E.g. if token IDs 1, 2 & 3 already existed, the user would need to start with token ID 4. That feels very awkward.

> Wouldn't it be better to keep the quantity and return an array of token IDs on a single mint event?

User  don't care about the TokenId. The should never see it in frontend unless they are programmer.
Event handling should be as simple as possible to save resources of the node
