### ISSUE TITLE
Refactor deployment scripts

### ISSUE THREAD

**Issue by chenzongxiong** [litentry/litentry-pallets#87]

**Comment by geastwood** [comment]
Can we please provide a simple comment when closing and also why reopen? It's helpful for others to understand.

**Comment by chenzongxiong** [comment]
The script simply updated. Then I closed. 
In the daily standup, we discussed and think it's better to synchronize with kaili. Then we reopen it. 
After syncing, we will close it again. 

It's related with devops scripts.

**Comment by chenzongxiong** [comment]
Use single source binary source from CI. In this way, we ensure  executable binary has the same checksum
