### ISSUE TITLE
Separate branches for that are ready for parachain and that are not

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/litentry-pallets#98]
**Description**
Currently all the pallet dependencies of our parachain are from upstream. But we will soon some our dapp pallets ready to onboard to parachain. In order to distinguish the ones that are ready (will have regular releases together with parachain repo) and the ones that are not, and make the integration with parachain repo easier, when we introduce our next feature pallet (it's soon), we need to have a new branch called `pipeline` where we preparing the pallets that have potential to onboard, and put all the ready to be integrated to parachain pallets in the dev branch

**Acceptance Criteria**
- [ ] Add a new `pipeline` branch and separate pallets accordingly

**Comment by wangminqi** [comment]
litentry-pallets is in abandoned mode. Pallets in use moved to parachain repo directly.
